name: DevOps Dashboard CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Application
        run: go build -o app

      - name: Build Docker Image
        run: docker build -t devops-dashboard .

      - name: Success
        run: echo "Pipeline completed successfully"